### ISSUE TITLE
[BE] DB User Table 설계

### ISSUE THREAD

**Issue by ksundong** [codesquad-member-2020/baseball-02#23]
### DB의 User Table 설계

- id, nickname, email, token 컬럼이 필요합니다.
- AUTO_INCREMENT 제약조건이 있는 컬럼의 이름을 id로 할지, ID 자체를 id로 할 지 논의하고 싶어요.

- 1안

| Index     | Column Name  | Type         | Constraint     |
| --------- | ------------ | ------------ | -------------- |
| PK        | id           | INT          | AUTO_INCREMENT |
|           | uid          | VARCHAR(25)  | NON_NULL       |
|           | nickname     | VARCHAR(25)  | NON_NULL       |
| UNIQUE(?) | email        | VARCHAR(255) | NON_NULL       |
|           | github_token | VARCHAR(255) | NON_NULL       |

- 2안

| Index     | Column Name  | Type         | Constraint     |
| --------- | ------------ | ------------ | -------------- |
| PK        | uid           | INT          | AUTO_INCREMENT |
|           | id          | VARCHAR(25)  | NON_NULL       |
|           | nickname     | VARCHAR(25)  | NON_NULL       |
| UNIQUE(?) | email        | VARCHAR(255) | NON_NULL       |
|           | github_token | VARCHAR(255) | NON_NULL       |

**Comment by kyungrae** [comment]
제가 잘못봤군요... 1번이 좋은것 같아요.

github 계정 id를 명시적으로 표현하기 위해 user_id or account_id로 하는것도 괜찮을 것같아요!

**Comment by ksundong** [comment]
user_id 로 하겠습니다!

**Comment by ksundong** [comment]
email이 Nullable해서 user_id 를 UNIQUE로 잡겠습니다!

**Comment by ksundong** [comment]
최종안 입니다.
| Index  | Column Name  | Type         | Constraint     |
| ------ | ------------ | ------------ | -------------- |
| PK     | id           | INT          | AUTO_INCREMENT |
| UNIQUE | user_id      | VARCHAR(25)  | NON_NULL       |
|        | nickname     | VARCHAR(25)  | NON_NULL       |
|        | email        | VARCHAR(255) | NULL           |
|        | github_token | VARCHAR(255) | NON_NULL       |

**Comment by ksundong** [comment]
```sql
CREATE TABLE user
(
    id           INT AUTO_INCREMENT,
    user_id      VARCHAR(25)  NOT NULL,
    nickname     VARCHAR(25)  NOT NULL,
    email        VARCHAR(255) NULL,
    github_token VARCHAR(255) NOT NULL,
    CONSTRAINT user_pk
        PRIMARY KEY (id)
);

CREATE UNIQUE INDEX user_user_id_uindex
    ON user (user_id);
```

**Comment by kyungrae** [comment]
ㅋㅋㅋㅋ 좋아요!!
아시고 있겠지만 unique 제약조건은 Type옆에 unique만 넣어도 할수 있어요!
