### ISSUE TITLE
[Team] 서버 클라이언트 API 통신 방법

### ISSUE THREAD

**Issue by kyungrae** [codesquad-member-2020/baseball-02#7]
# 방법 1

## 백엔드 역할

클라이언트에서 pitch API를 호출하면 가능한 모든 상황을 서버에서 처리한다.
ex) pitch 결과(ball, strike, out), 볼 카운트(ball, strike, out), 주자 관리, 점수 조건, 타석 관리

## 클라이언트 역할

각 회에 대한 점수 이력 관리 및 게임에서 선수 기록 이력 관리
ex) 상세 점수 팝업 및 선수 명단 팝업

# 방법 2

## 백앤드 역할

1. 클라이언트에서 pitch API를 호출할 때 타자와 투수에 대한 정보를 함께 요청한다.
ex) pitch 결과(ball, strike, out)를 리턴하고 그에 대한 선수 기록과 한 회에 대한 점수 정보를 업데이트한다.
2. 인게임 선수 결과 API 제공
3. 각 회에 대한 점수 API 제공

## 클라이언트 역할

1. 사용자가 pitch 버튼을 눌렀을 때 타자와 투수에 대한 정보를 함께 API로 요청한다.
2. API에 대한 결과를 스트라이크, 볼, 아웃을 상태로 관리한다.
3. 3 스트라이크, 4 볼, 3 아웃과 같은 이벤트를 처리한다.
4. 타석관리

**Comment by ksundong** [comment]
https://hackmd.io/_9Wb4q2VRlOdlvw-IERZTQ?both
